### ISSUE TITLE
The ability to read titles from the YAML.

### ISSUE THREAD

**Issue by ivkorolyov** [joshuatazrein/obsidian-link-tree#1]
**Is your feature request related to a problem? Please describe.**
I append unique codes to all of my file names but I use https://github.com/snezhig/obsidian-front-matter-title to keep them from rendering the unique code portion in the file tree.

**Describe the solution you'd like**
The Front Matter Title author has an NPM package that provides an API in to the plugin's configuration, so maybe including that? https://github.com/Snezhig/front-matter-plguin-api-provider

**Additional context**
![Screenshot_20230901_213640_Obsidian](https://github.com/joshuatazrein/obsidian-link-tree/assets/50589503/3432c13b-6c3f-4751-908c-e80b092ecb41)

**Comment by joshuatazrein** [comment]
I'm confused what you want specifically. Do you want to provide the ability to read titles from the YAML of a note via this API, or just to cut unique codes from the filename?

**Comment by ivkorolyov** [comment]
I want to provide the ability to read titles from the YAML of a note via this API.

**Comment by joshuatazrein** [comment]
Ahh OK. I can look into that, it's probably not going to be too hard. I've added it to "considering."
