### ISSUE TITLE
How are notes sorted? Can I customize it?

### ISSUE THREAD

**Issue by wenbopeng** [joshuatazrein/obsidian-link-tree#3]
**Describe your idea**
How are notes sorted? Can I customize it?
**Why is this important for Link Tree?**
If there are a lot of notes, it's difficult for me to locate them accurately. It would be a good idea if I could sort them based on the order they appear in the notes, or creation time, or some other.

**Comment by j-palindrome** [comment]
For now, you can filter notes with searching. Normally they are sorted alphabetically. I can try sorting based on creation/edit time, added that to changelog.

**Comment by j-palindrome** [comment]
This will be in the upcoming release.

**Comment by wenbopeng** [comment]
@joshuatazrein I use `created` and `modified` and `rating` in frontmatter to record time and rating. I must use created to fix the creation time of notes, because changing computers or restoring backups will cause ctime or cday to change, but created will never change. I want to use a custom dv key/frontmatter like created or rating to sort.

It is also a good idea to display outlink/inlink/two-waylink separately

ps: I have a dependency on `obsidian-link-tree`. I used to write the dataview code block myself, but your solution is shocking.💕💕💕
